<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="admin.aspx.cs" Inherits="eVisaProcessing.WebForm2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>E-Visa | Admin Panel</title>
    <style>
        * {
            margin: 0 auto;
            text-align: center;
        }

        .wrapper {
            padding: 2rem;
            display: flex;
            background-color: lightcoral;
        }

        .box {
            background-color: #ffffffa6;
            padding: 1.5rem;
            border-radius: 10%;
        }

        h2 {
            padding: 3rem;
        }

        h3 {
            padding: 2rem;
        }

        input[type=text] {
            width: 80px;
        }
    </style>
</head>
<body ">
    <h2>Welcome to Admin Panel!</h2>
    <form id="form1" runat="server">
        <div class="wrapper">
            <div class="box">
                <h3>Add HR Details</h3>
                <asp:Label ID="Label1" runat="server" Text="ID"></asp:Label>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TextBox1" runat="server" ValidationGroup="hr"></asp:TextBox>

                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="TextBox1" ErrorMessage="* Required" ForeColor="Red" ValidationGroup="hr"></asp:RequiredFieldValidator>
                <br />
                <br />
                <asp:Label ID="Label2" runat="server" Text="Password"></asp:Label>
                &nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TextBox2" runat="server" ValidationGroup="hr"></asp:TextBox>

                <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="TextBox2" ErrorMessage="* Required" ForeColor="Red" ValidationGroup="hr"></asp:RequiredFieldValidator>
                <br />
                <br />
                <asp:Label ID="Label3" runat="server" Text="Name"></asp:Label>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TextBox3" runat="server" ValidationGroup="hr"></asp:TextBox>

                <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="TextBox3" ErrorMessage="* Required" ForeColor="Red" ValidationGroup="hr"></asp:RequiredFieldValidator>
                <br />
                <br />
                <asp:Label ID="Label4" runat="server" Text="Email"></asp:Label>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TextBox4" runat="server" ValidationGroup="hr"></asp:TextBox>

                <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ControlToValidate="TextBox4" ErrorMessage="* Required" ForeColor="Red" ValidationGroup="hr"></asp:RequiredFieldValidator>
                <br />
                <br />
                <asp:Label ID="Label5" runat="server" Text="Phone"></asp:Label>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TextBox5" runat="server" ValidationGroup="hr"></asp:TextBox>

                <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" ControlToValidate="TextBox5" ErrorMessage="* Required" ForeColor="Red" ValidationGroup="hr"></asp:RequiredFieldValidator>
                <br />
                <br />
                <asp:Label ID="Label6" runat="server" Text="Address"></asp:Label>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TextBox6" runat="server" ValidationGroup="hr"></asp:TextBox>

                <asp:RequiredFieldValidator ID="RequiredFieldValidator6" runat="server" ControlToValidate="TextBox6" ErrorMessage="* Required" ForeColor="Red" ValidationGroup="hr"></asp:RequiredFieldValidator>
                <br />
                <br />
                <asp:Button ID="Button1" runat="server" BackColor="#009933" OnClick="Button1_Click" Text="Insert" ValidationGroup="hr" />
&nbsp;&nbsp;&nbsp;
                <asp:Button ID="Button2" runat="server" BackColor="#CC0000" Text="Reset" ValidationGroup="hr" />
                <br />

            </div>
            <div class="box">
                <h3>Manage HR details</h3>
                <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowEditing="GridView1_RowEditing" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowUpdating="GridView1_RowUpdating" OnPageIndexChanging="GridView1_PageIndexChanging" OnRowDeleting="GridView1_RowDeleting" PageSize="5">
                </asp:GridView>
            </div>
        </div>
                <div class="wrapper">
            <div class="box">
                <h3>Add Employee Details</h3>
                <asp:Label ID="Label7" runat="server" Text="ID"></asp:Label>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TextBox7" runat="server" ValidationGroup="emp"></asp:TextBox>

                <asp:RequiredFieldValidator ID="RequiredFieldValidator7" runat="server" ControlToValidate="TextBox7" ErrorMessage="* Required" ForeColor="Red" ValidationGroup="emp"></asp:RequiredFieldValidator>
                <br />
                <br />
                <asp:Label ID="Label8" runat="server" Text="Password"></asp:Label>
                &nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TextBox8" runat="server" ValidationGroup="emp"></asp:TextBox>

                <asp:RequiredFieldValidator ID="RequiredFieldValidator8" runat="server" ControlToValidate="TextBox8" ErrorMessage="* Required" ForeColor="Red" ValidationGroup="emp"></asp:RequiredFieldValidator>
                <br />
                <br />
                <asp:Label ID="Label9" runat="server" Text="Name"></asp:Label>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TextBox9" runat="server" ValidationGroup="emp"></asp:TextBox>

                <asp:RequiredFieldValidator ID="RequiredFieldValidator9" runat="server" ControlToValidate="TextBox9" ErrorMessage="* Required" ForeColor="Red" ValidationGroup="emp"></asp:RequiredFieldValidator>
                <br />
                <br />
                <asp:Label ID="Label10" runat="server" Text="Email"></asp:Label>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TextBox10" runat="server" ValidationGroup="emp"></asp:TextBox>

                <asp:RequiredFieldValidator ID="RequiredFieldValidator10" runat="server" ControlToValidate="TextBox10" ErrorMessage="* Required" ForeColor="Red" ValidationGroup="emp"></asp:RequiredFieldValidator>
                <br />
                <br />
                <asp:Label ID="Label11" runat="server" Text="Phone"></asp:Label>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TextBox11" runat="server" ValidationGroup="emp"></asp:TextBox>

                <asp:RequiredFieldValidator ID="RequiredFieldValidator11" runat="server" ControlToValidate="TextBox11" ErrorMessage="* Required" ForeColor="Red" ValidationGroup="emp"></asp:RequiredFieldValidator>
                <br />
                <br />
                <asp:Label ID="Label12" runat="server" Text="Address"></asp:Label>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TextBox12" runat="server" ValidationGroup="emp"></asp:TextBox>

                <asp:RequiredFieldValidator ID="RequiredFieldValidator12" runat="server" ControlToValidate="TextBox12" ErrorMessage="* Required" ForeColor="Red" ValidationGroup="emp"></asp:RequiredFieldValidator>
                <br />
                <br />
                <asp:Button ID="Button3" runat="server" BackColor="#009933" OnClick="Button3_Click" Text="Insert" ValidationGroup="emp" />
&nbsp;&nbsp;&nbsp;
                <asp:Button ID="Button4" runat="server" BackColor="#CC0000" Text="Reset" ValidationGroup="emp" />
                <br />

            </div>
            <div class="box">
                <h3>Manage Employee details</h3>
                <asp:GridView ID="GridView2" runat="server" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowEditing="GridView2_RowEditing" OnSelectedIndexChanged="Page_Load" OnRowCancelingEdit="GridView2_RowCancelingEdit" OnRowUpdating="GridView2_RowUpdating" OnPageIndexChanging="GridView2_PageIndexChanging" OnRowDeleting="GridView2_RowDeleting" PageSize="5">
                </asp:GridView>
            </div>
                    </div>
        <div class="wrapper">
            <div class="box">
                <h3>Insert Visa Application Details</h3>
                <asp:Label ID="Label13" runat="server" Text="ApplicationID"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TextBox13" runat="server"></asp:TextBox>
                <br />
                <br />
                <asp:Label ID="Label14" runat="server" Text="Name"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TextBox14" runat="server"></asp:TextBox>
                <br />
                <br />
                <asp:Label ID="Label15" runat="server" Text=" Contact No"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TextBox15" runat="server"></asp:TextBox>
                <br />
                <br />
                <asp:Label ID="Label16" runat="server" Text="Visa Status"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:DropDownList ID="DropDownList1" runat="server">
                    <asp:ListItem>applied</asp:ListItem>
                    <asp:ListItem>waiting</asp:ListItem>
                    <asp:ListItem>approved</asp:ListItem>
                    <asp:ListItem>declined</asp:ListItem>
                </asp:DropDownList>
                <br />
                <br />
                <asp:Label ID="Label17" runat="server" Text="Interview Status"></asp:Label>
&nbsp;&nbsp;
                <asp:DropDownList ID="DropDownList2" runat="server">
                    <asp:ListItem>scheduled</asp:ListItem>
                    <asp:ListItem>completed</asp:ListItem>
                    <asp:ListItem>failed</asp:ListItem>
                </asp:DropDownList>
                <br />
                <br />
                <asp:Label ID="Label18" runat="server" Text="Final Report"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:DropDownList ID="DropDownList3" runat="server">
                    <asp:ListItem>approved</asp:ListItem>
                    <asp:ListItem>declined</asp:ListItem>
                </asp:DropDownList>
                <br />
                <br />
                <asp:Button ID="Button5" runat="server" BackColor="#009933" Text="Insert" OnClick="Button5_Click" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Button ID="Button6" runat="server" BackColor="#CC0000" Text="Cancel" />
             </div>
            <div class="box">
                <h3>Visa Details</h3>
                <asp:GridView ID="GridView3" runat="server">
                </asp:GridView>
            </div>
        </div>
    </form>
</body>
</html>
